name: flagcicd-Hopper-Build-And-Test

on:
  schedule:
    - cron: '0 21 * * *'
  push:
    branches: [ "triton_v3.4.x", "triton_v3.5.x" ]
  pull_request:
    branches: [ "triton_v3.4.x", "triton_v3.5.x" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  flagcicd-hopper-build-and-test:
    runs-on: [flagcicd-flagtree-nvidia3.6]
    container:
      image: harbor.baai.ac.cn/flagtree/flagtree-3.6.x-py312-torch2.8.0a0_5228986c39.nv25.05-ubuntu24.04:202603
      options: --uts=host --ipc=host --privileged  --ulimit stack=67108864 --ulimit memlock=-1 --security-opt seccomp=unconfined --gpus=all
      volumes:
        - /mnt/airs-business/cicd:/mnt/airs-business/cicd

    if: ${{ github.repository == 'FlagTree/flagtree' || github.repository == 'flagos-ai/flagtree' }}
    steps:
      - name: Smart Checkout
        uses: flagos-ai/FlagTree/.github/actions/smart-checkout@main
        with:
          checkout_version: 'v6'

      - name: Set safe directory
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Check if backend-relevant files changed
        id: check_backend
        uses: flagos-ai/FlagTree/.github/actions/check-backend-changed@main
        with:
          backend: nvidia

      - name: Detect Target Branch
        shell: bash
        run: |
          set -x
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            TARGET_BRANCH="${{ github.base_ref }}"
          else
            TARGET_BRANCH="${{ github.ref_name }}"
          fi
          echo "TARGET_BRANCH=$TARGET_BRANCH" >> $GITHUB_ENV
          echo "TARGET_BRANCH=$TARGET_BRANCH"

      - name: FlagTree Build on NVidia (triton_v3.4.x branch)
        if: ${{ steps.check_backend.outputs.should_skip != 'true' && env.TARGET_BRANCH == 'triton_v3.4.x' }}
        shell: bash
        run: |
          set -x
          pip uninstall -y triton
          MAX_JOBS=32 python3.12 -m pip install . --no-build-isolation

      - name: FlagTree Build on NVidia (triton_v3.5.x branch)
        if: ${{ steps.check_backend.outputs.should_skip != 'true' && env.TARGET_BRANCH == 'triton_v3.5.x' }}
        shell: bash
        run: |
          set -x
          pip uninstall -y triton
          source ~/env-3.5.sh
          MAX_JOBS=32 python3.12 -m pip install . --no-build-isolation

      - name: FlagTree Test on NVidia
        if: steps.check_backend.outputs.should_skip != 'true'
        shell: bash
        run: |
          set -x
          python3.12 -m pytest -s python/test/unit/cuda
          python3.12 -m pytest -s python/test/unit/instrumentation
          python3.12 -m pytest -s python/test/unit/language \
              --ignore=python/test/unit/language/test_line_info.py
          python3.12 -m pytest -s python/test/unit/runtime
          if [ -d "python/test/operators" ]; then
            python3.12 -m pytest -s python/test/operators
          fi
